general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

# Dim screen after 3 min idle, restore on activity
listener {
    timeout = 180
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Lock after 5 min idle, greet on return
listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = notify-send "You are back !"
}

# Suspend after 10 min idle
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
