general {
    disable_loading_bar = true
    grace = 5
    hide_cursor = true
    no_fade_in = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 400, 65
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(126, 152, 232)
    inner_color = rgb(20, 20, 21)
    font_color = rgb(205, 205, 205)
    font_family = JetBrainsMono Nerd Font
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <i>Enter Password</i>
    hide_input = false
    rounding = 0
    check_color = rgb(127, 165, 99)
    fail_color = rgb(216, 100, 126)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -20
    halign = center
    valign = center
}
