max_gamma = 100

# Daytime: no color change
profile {
    time = 06:00
    identity = true
}

# 6pm - 6am: mildly warm
profile {
    time = 18:00
    identity = false
    temperature = 4500
    gamma = 1.0
}
