[main]
font=Iosevka Nerd Font Mono:size=12, Noto Color Emoji:size=15
pad=10x0 center
resize-by-cells=no

[colors-dark]
#alpha=1
alpha=0.80
blur=yes
foreground=cdcdcd
background=141415

regular0=141415
regular1=d8647e
regular2=7fa563
regular3=e0a363
regular4=6e94b2
regular5=bb9dbd
regular6=9bb4bc
regular7=cdcdcd

bright0=606079
bright1=c48282
bright2=b4d4cf
bright3=f3be7c
bright4=7e98e8
bright5=aeaed1
bright6=90a0b5
bright7=ffffff

selection-foreground=cdcdcd
selection-background=333738
